# Everything in the `figs` directory
#figs := $(wildcard figs/*)

#pres.pdf : pres.tex $(figs)
#pdflatex pres.tex

#figs/normal.pdf : normal.R
#R CMD BATCH --vanilla normal.R 

clean :
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *.Rout
